# Generated by Django 4.0.6 on 2022-07-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dang_nhap', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mat_khau', models.CharField(max_length=100)),
            ],
        ),
    ]
